///////////////////////////////////////////////////////////
//  Item.cs
//  Implementation of the Class Item
//  Generated by Enterprise Architect
//  Created on:      26-апр-2016 21:59:57
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Item : IHaveNameDescription {

		public ConsoleApplication1.NameDescription m_NameDescription;

		public Item(){

		}

		~Item(){

		}

		public virtual void Dispose(){

		}

	}//end Item

}//end namespace ConsoleApplication1