///////////////////////////////////////////////////////////
//  AI.cs
//  Implementation of the Class AI
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:33:01
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public class AI {

		public AI(){

		}

		~AI(){

		}

		public virtual void Dispose(){

		}

	}//end AI

}//end namespace ConsoleApplication1