///////////////////////////////////////////////////////////
//  AIHero.cs
//  Implementation of the Class AIHero
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:29:16
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class AIHero : AI {

		public AIHero(){

		}

		~AIHero(){

		}

		public override void Dispose(){

		}

	}//end AIHero

}//end namespace ConsoleApplication1