///////////////////////////////////////////////////////////
//  Vizualizer.cs
//  Implementation of the Class Vizualizer
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:36:10
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
    /// <summary>
    /// для визуализации
    /// </summary>
	public class Vizualizer {
        /// <summary>
        /// ссылка на карту
        /// </summary>
		protected ConsoleApplication1.Map m_Map;
        /// <summary>
        /// сылка на игрока
        /// </summary>
		protected ConsoleApplication1.Unit hero;

        /// <summary>
        /// отображает карту
        /// </summary>
        public void Show()
        {//https://github.com/MinnullinIrek/rogelike.git
            for (int i = 0; i < m_Map.GetLength(0); i++)
            {
                for (int j = 0; j < m_Map.GetLength(1); j++)
                {

                }
            }
        }


		public Vizualizer()
        {

		}

		~Vizualizer(){

		}

		public virtual void Dispose(){

		}

	}//end Vizualizer

}//end namespace ConsoleApplication1