///////////////////////////////////////////////////////////
//  IHaveNameDescription.cs
//  Implementation of the Interface IHaveNameDescription
//  Generated by Enterprise Architect
//  Created on:      26-апр-2016 21:59:53
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public interface IHaveNameDescription  {
        string name
        {
            get;
        }

        string description
        {
            get;          
        }


    }//end IHaveNameDescription

}//end namespace ConsoleApplication1