///////////////////////////////////////////////////////////
//  Level.cs
//  Implementation of the Class Level
//  Generated by Enterprise Architect
//  Created on:      26-апр-2016 22:00:23
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public class Level {

		public Level(){

		}

		~Level(){

		}

		public virtual void Dispose(){

		}

	}//end Level

}//end namespace ConsoleApplication1