///////////////////////////////////////////////////////////
//  NameDescription.cs
//  Implementation of the Class NameDescription
//  Generated by Enterprise Architect
//  Created on:      26-апр-2016 21:59:47
//  Original author: admin
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace ConsoleApplication1 {
	public class NameDescription {

        public readonly KeyValuePair<string,string> nameDescription;

		public NameDescription(string name, string description)
        {
            nameDescription = new KeyValuePair<string, string>(name, description);
		}

        public string name
        {
            get { return nameDescription.Key; }
            private set { }
        }

        public string description
        {
            get { return nameDescription.Value; }
            private set { }
        }


        ~NameDescription(){

		}

		public virtual void Dispose(){

		}

	}//end NameDescription

}//end namespace ConsoleApplication1