///////////////////////////////////////////////////////////
//  Vizualizer.cs
//  Implementation of the Class Vizualizer
//  Generated by Enterprise Architect
//  Created on:      08-май-2016 13:44:05
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Vizualizer {

		protected ConsoleApplication1.Map m_Map;
		protected ConsoleApplication1.Unit m_Unit;

		public Vizualizer(){

		}

		~Vizualizer(){

		}

		public virtual void Dispose(){

		}

	}//end Vizualizer

}//end namespace ConsoleApplication1