///////////////////////////////////////////////////////////
//  Armour.cs
//  Implementation of the Class Armour
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:37
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Armour : UsingItem, IArmour {

		public Armour(){

		}

		~Armour(){

		}

		public override void Dispose(){

		}

	}//end Armour

}//end namespace ConsoleApplication1