///////////////////////////////////////////////////////////
//  Bag.cs
//  Implementation of the Class Bag
//  Generated by Enterprise Architect
//  Created on:      23-апр-2016 15:23:15
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public class Bag {
		public Item m_Item;


		public Bag(){

		}

		~Bag(){

		}

		public virtual void Dispose(){

		}

	}//end Bag

}//end namespace ConsoleApplication1