///////////////////////////////////////////////////////////
//  IArmour.cs
//  Implementation of the Interface IArmour
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:26
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public interface IArmour : IWearingItem  {

	}//end IArmour

}//end namespace ConsoleApplication1