///////////////////////////////////////////////////////////
//  IBonus.cs
//  Implementation of the Class IBonus
//  Generated by Enterprise Architect
//  Created on:      26-апр-2016 22:01:40
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class IBonus {

		public ConsoleApplication1.CTime m_CTime;

		public IBonus(){

		}

		~IBonus(){

		}

		public virtual void Dispose(){

		}

	}//end IBonus

}//end namespace ConsoleApplication1