///////////////////////////////////////////////////////////
//  Item.cs
//  Implementation of the Class Item
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:31:02
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public class Item {

		public Item(){

		}

		~Item(){

		}

		public virtual void Dispose(){

		}

	}//end Item

}//end namespace ConsoleApplication1