///////////////////////////////////////////////////////////
//  IWearingItem.cs
//  Implementation of the Interface IWearingItem
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:08
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public interface IWearingItem  {

	}//end IWearingItem

}//end namespace ConsoleApplication1