///////////////////////////////////////////////////////////
//  Iweapon.cs
//  Implementation of the Interface Iweapon
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:18
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public interface Iweapon : IWearingItem  {

	}//end Iweapon

}//end namespace ConsoleApplication1