///////////////////////////////////////////////////////////
//  Poution.cs
//  Implementation of the Class Poution
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:43
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Poution : UsingItem {

		public Poution(){

		}

		~Poution(){

		}

		public override void Dispose(){

		}

	}//end Poution

}//end namespace ConsoleApplication1