///////////////////////////////////////////////////////////
//  UsingItem.cs
//  Implementation of the Class UsingItem
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:49
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class UsingItem : Item {

		public BonusList m_BonusList;

		public UsingItem(){

		}

		~UsingItem(){

		}

		public override void Dispose(){

		}

	}//end UsingItem

}//end namespace ConsoleApplication1