///////////////////////////////////////////////////////////
//  Weapon.cs
//  Implementation of the Class Weapon
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:32
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Weapon : UsingItem, Iweapon {

		public Weapon(){

		}

		~Weapon(){

		}

		public override void Dispose(){

		}

	}//end Weapon

}//end namespace ConsoleApplication1