///////////////////////////////////////////////////////////
//  Cell.cs
//  Implementation of the Class Cell
//  Generated by Enterprise Architect
//  Created on:      23-апр-2016 15:22:57
//  Original author: admin
///////////////////////////////////////////////////////////



using System.Collections.Generic;
using ConsoleApplication1;
namespace ConsoleApplication1 {
	/// <summary>
	/// €чейка
	/// </summary>
	public class Cell {

		/// <summary>
		/// кто стоит в данной €чейке
		/// </summary>
		private IFiller m_IFiller;
		/// <summary>
		/// список вещей лежащих в данной €чейке
		/// </summary>
		private Bag m_Bag;
		/// <summary>
		/// координаты
		/// </summary>
        readonly private KeyValuePair<uint, uint> coord;

		public Cell(uint x, uint y)
        {
            coord = new KeyValuePair<uint, uint>(x, y);
		}

		~Cell(){

		}

		public virtual void Dispose(){

		}

		/// <summary>
		/// пуста€ ли €чейка
		/// </summary>
		public bool IsEmpty(){
			return (m_IFiller != null)?m_IFiller.IsVisible():true;
		}

	}//end Cell

}//end namespace ConsoleApplication1