///////////////////////////////////////////////////////////
//  IFiller.cs
//  Implementation of the Interface IFiller
//  Generated by Enterprise Architect
//  Created on:      23-апр-2016 15:23:02
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public interface IFiller     {

	
		/// <summary>
		/// видим ли объект
		/// </summary>
		bool IsVisible();
}//end IFiller

}//end namespace ConsoleApplication1