///////////////////////////////////////////////////////////
//  Map.cs
//  Implementation of the Class Map
//  Generated by Enterprise Architect
//  Created on:      23-апр-2016 15:22:51
//  Original author: admin
///////////////////////////////////////////////////////////




using System;
using ConsoleApplication1;
namespace ConsoleApplication1 {
	/// <summary>
	/// карта
	/// </summary>
	public class Map {

		protected ConsoleApplication1.Cell[,] m_Cell;

		public Map(){

		}

        /// <summary>
        /// получить длину массива
        /// </summary>
        /// <param name="v"></param>
        /// <returns></returns>
        public int GetLength(int v)
        {
            return m_Cell.GetLength(v);
        }

        /// <summary>
        /// создает карту
        /// </summary>
        /// <param name="xLength">размер по х</param>
        /// <param name="yLength">размер по у</param>
        public void GenerateMap(uint xLength, uint yLength)
        {
            m_Cell = new Cell[xLength, yLength];

            for (uint x = 0; x < xLength; x++)
                for (uint y = 0; y < xLength; y++)
                    m_Cell[x, y] = new Cell(x, y);
        }


        ~Map(){

		}

		public virtual void Dispose(){

		}

	}//end Map

}//end namespace ConsoleApplication1