///////////////////////////////////////////////////////////
//  CTime.cs
//  Implementation of the Class CTime
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:27:50
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public class CTime {

		public CTime(){

		}

		~CTime(){

		}

		public virtual void Dispose(){

		}

	}//end CTime

}//end namespace ConsoleApplication1