///////////////////////////////////////////////////////////
//  CTimeHero.cs
//  Implementation of the Class CTimeHero
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:28:01
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class CTimeHero : CTime {

		public CTimeHero(){

		}

		~CTimeHero(){

		}

		public override void Dispose(){

		}

	}//end CTimeHero

}//end namespace ConsoleApplication1