///////////////////////////////////////////////////////////
//  CTimeAi.cs
//  Implementation of the Class CTimeAi
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:27:46
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class CTimeAi : CTime {

		public CTimeAi(){

		}

		~CTimeAi(){

		}

		public override void Dispose(){

		}

	}//end CTimeAi

}//end namespace ConsoleApplication1