///////////////////////////////////////////////////////////
//  BodySlot.cs
//  Implementation of the Class BodySlot
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:00
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class BodySlot {

		public IWearingItem m_IWearingItem;

		public BodySlot(){

		}

		~BodySlot(){

		}

		public virtual void Dispose(){

		}

	}//end BodySlot

}//end namespace ConsoleApplication1