///////////////////////////////////////////////////////////
//  Body.cs
//  Implementation of the Class Body
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:29:05
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Body {

		public BodyPart m_BodyPart;

		public Body(){

		}

		~Body(){

		}

		public virtual void Dispose(){

		}

	}//end Body

}//end namespace ConsoleApplication1