///////////////////////////////////////////////////////////
//  BodyPart.cs
//  Implementation of the Class BodyPart
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:29:48
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class BodyPart {

		public BodySlot m_BodySlot;

		public BodyPart(){

		}

		~BodyPart(){

		}

		public virtual void Dispose(){

		}

	}//end BodyPart

}//end namespace ConsoleApplication1