///////////////////////////////////////////////////////////
//  Charachteristic.cs
//  Implementation of the Class Charachteristic
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:29:13
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Charachteristic {

		public Params m_Params;

		public Charachteristic(){

		}

		~Charachteristic(){

		}

		public virtual void Dispose(){

		}

	}//end Charachteristic

}//end namespace ConsoleApplication1