///////////////////////////////////////////////////////////
//  IHaveExp.cs
//  Implementation of the Interface IHaveExp
//  Generated by Enterprise Architect
//  Created on:      26-апр-2016 22:00:18
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public interface IHaveExp  {

	}//end IHaveExp

}//end namespace ConsoleApplication1