///////////////////////////////////////////////////////////
//  IMover.cs
//  Implementation of the Interface IMover
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:26:58
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public interface IMover : IFiller  {

	}//end IMover

}//end namespace ConsoleApplication1