///////////////////////////////////////////////////////////
//  Params.cs
//  Implementation of the Class Params
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:29:09
//  Original author: admin
///////////////////////////////////////////////////////////




namespace ConsoleApplication1 {
	public class Params {

		public Params(){

		}

		~Params(){

		}

		public virtual void Dispose(){

		}

	}//end Params

}//end namespace ConsoleApplication1