///////////////////////////////////////////////////////////
//  Unit.cs
//  Implementation of the Class Unit
//  Generated by Enterprise Architect
//  Created on:      23-апр-2016 15:23:09
//  Original author: admin
///////////////////////////////////////////////////////////




using System;
using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Unit : IFiller, IHaveExp, IHaveNameDescription {

		public class Mover : IMover {

			public Mover(){

			}

			~Mover(){

			}

			public virtual void Dispose(){

			}

			/// <summary>
			/// видим ли объект
			/// </summary>
			public bool IsVisible(){

				return false;
			}

		}//end Mover

		protected ConsoleApplication1.Bag m_Bag;
		public ConsoleApplication1.CTime m_CTime;
		public ConsoleApplication1.Body m_Body;
		public ConsoleApplication1.Charachteristic m_Charachteristic;
		public ConsoleApplication1.AI m_AI;
		public ConsoleApplication1.BonusList m_BonusList;
		public ConsoleApplication1.Level m_Level;
		public ConsoleApplication1.NameDescription m_NameDescription;


        public string name
        {
            get
            {
                return m_NameDescription.name;
            }
        }

        public string description
        {
            get
            {
                return m_NameDescription.description;
            }
        }

        public Unit(){

		}

		~Unit(){

		}

		public virtual void Dispose(){

		}

		/// <summary>
		/// видим ли объект
		/// </summary>
		public bool IsVisible(){

			return false;
		}

	}//end Unit

}//end namespace ConsoleApplication1