///////////////////////////////////////////////////////////
//  Whall.cs
//  Implementation of the Class Whall
//  Generated by Enterprise Architect
//  Created on:      23-апр-2016 15:23:05
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class Whall : IFiller {

		public Whall(){

		}

		~Whall(){

		}

		public virtual void Dispose(){

		}

		/// <summary>
		/// видим ли объект
		/// </summary>
		public bool IsVisible()
        {
			return true;
		}

	}//end Whall

}//end namespace ConsoleApplication1