///////////////////////////////////////////////////////////
//  BonusList.cs
//  Implementation of the Class BonusList
//  Generated by Enterprise Architect
//  Created on:      24-апр-2016 7:30:55
//  Original author: admin
///////////////////////////////////////////////////////////




using ConsoleApplication1;
namespace ConsoleApplication1 {
	public class BonusList {

		public IBonus m_IBonus;

		public BonusList(){

		}

		~BonusList(){

		}

		public virtual void Dispose(){

		}

	}//end BonusList

}//end namespace ConsoleApplication1